# Generated by Django 3.2 on 2021-11-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_requisicao', models.CharField(choices=[('adicao', 'Adição'), ('exclusao', 'Exclusão'), ('atualizacao', 'Atualização')], max_length=255)),
                ('conteudo_atualizar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteudo_atualizar', to='conteudos.conteudo')),
                ('conteudo_pendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo_pendente', to='conteudos.conteudo')),
            ],
        ),
    ]
