# Generated by Django 3.2.9 on 2022-10-22 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requisicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaoformulario',
            name='data_requisicao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
