# Generated by Django 3.2.9 on 2022-10-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='fotoperfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
