# Generated by Django 3.2.9 on 2022-10-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20221010_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfildata',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='perfildata',
            name='foto',
            field=models.ImageField(blank=True, upload_to='userprofile', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='usuário'),
        ),
    ]
