# Generated by Django 3.2.9 on 2022-10-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20221011_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfildata',
            old_name='foto',
            new_name='profile_picture',
        ),
    ]
