# Generated by Django 3.2.9 on 2022-10-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rename_foto_perfildata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildata',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='fotoperfil', verbose_name='foto'),
        ),
    ]
