# Generated by Django 3.2.9 on 2022-10-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_perfildata_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfildata',
            old_name='profile_picture',
            new_name='foto',
        ),
    ]
