# Generated by Django 3.2.9 on 2022-11-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_perfildata_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildata',
            name='sobre',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
