# Generated by Django 3.2.9 on 2022-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_perfildata_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='silenciado',
            field=models.CharField(blank=True, choices=[('prazo_medio', '15 Dias'), ('prazo_grande', '30 Dias')], max_length=50, verbose_name='Tempo Mutado'),
        ),
    ]
