# Generated by Django 3.2.9 on 2022-11-21 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_perfil_email_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='\\([0-9]{2}\\) 9?[0-9]{4}-[0-9]{4}')], verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
