# Generated by Django 3.2.9 on 2022-11-25 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_perfil_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='\\([0-9]{2}\\) 9?[0-9]{4}-[0-9]{4}')], verbose_name='Telefone'),
        ),
    ]
