# Generated by Django 3.2.9 on 2022-11-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_perfil_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email_confirmado',
            field=models.BooleanField(default=True),
        ),
    ]
