# Generated by Django 3.2.9 on 2022-11-07 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0040_auto_20221022_1646'),
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSinalizacaoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255, verbose_name='Comentário')),
                ('acao', models.CharField(choices=[('parece_ok', 'Parece Ok'), ('remover', 'Remover')], max_length=255, verbose_name='Ação')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('usuario', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSinalizacaoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacao', models.CharField(max_length=255, verbose_name='Notificação')),
                ('status', models.CharField(choices=[('aguardando_edicao', 'Aguardando Edição'), ('edicao_concluida', 'Edição Concluída')], default='aguardando_edicao', max_length=255, verbose_name='Ação')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudos.conteudo')),
                ('usuario', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSinalizacaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacao', models.CharField(max_length=255, null=True, verbose_name='Notificação')),
                ('acao', models.CharField(choices=[('excluir_conta', 'Excluir Conta'), ('silenciar_perfil', 'Silenciar Perfil'), ('enviar_notificacao', 'Enviar Notificação'), ('parece_ok', 'Parece Ok')], default='excluir_conta', max_length=255, verbose_name='Ação')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.CharField(max_length=100, verbose_name='Perfil Sinalizado')),
                ('usuario', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSilenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silenciado', models.CharField(blank=True, choices=[('prazo_medio', '15 Dias'), ('prazo_grande', '30 Dias')], max_length=50, verbose_name='Tempo Mutado')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Perfil Silenciado')),
            ],
        ),
        migrations.CreateModel(
            name='SinalizacaoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificador', models.CharField(blank=True, choices=[('Negative', 'Negativo')], max_length=255)),
                ('tipo_sinalizacao', models.CharField(choices=[('rude', 'Rude')], max_length=255)),
                ('apuracao_status', models.CharField(blank=True, choices=[('parece_ok', 'Parece Ok')], max_length=255)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentario', to='conteudos.comentario')),
                ('usuario', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaocomentario_usuario_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SinalizacaoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificado', models.BooleanField(default=False)),
                ('classificador', models.CharField(blank=True, choices=[('Negative', 'Negativo')], max_length=255)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Conteudo', to='conteudos.conteudo')),
                ('sinalizacoes_conteudo', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoconteudo_sinalizacoes_conteudo_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Conteúdo')),
                ('sinalizacoes_descricao', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoconteudo_sinalizacoes_descricao_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Descrição')),
                ('sinalizacoes_secao', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoconteudo_sinalizacoes_secao_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Seção')),
                ('sinalizacoes_tecnologia', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoconteudo_sinalizacoes_tecnologia_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Tecnologia')),
                ('sinalizacoes_titulo', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoconteudo_sinalizacoes_titulo_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Título')),
            ],
        ),
        migrations.CreateModel(
            name='SinalizacaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificado', models.BooleanField(default=False)),
                ('classificador', models.CharField(blank=True, choices=[('Negative', 'Negativo')], max_length=30)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Conteudo', to=settings.AUTH_USER_MODEL)),
                ('sinalizacoes_condutas', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoperfil_sinalizacoes_condutas_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Condutas')),
                ('sinalizacoes_descricao', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoperfil_sinalizacoes_descricao_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Descrição')),
                ('sinalizacoes_foto', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoperfil_sinalizacoes_foto_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Foto')),
                ('sinalizacoes_nome', models.ManyToManyField(blank=True, related_name='_denuncias_sinalizacaoperfil_sinalizacoes_nome_+', to=settings.AUTH_USER_MODEL, verbose_name='Sinalizações Nome')),
            ],
        ),
        migrations.DeleteModel(
            name='Denuncias',
        ),
    ]
