# Generated by Django 3.2.9 on 2022-11-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_auto_20221107_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinalizacaoperfil',
            name='silenciado',
            field=models.BooleanField(default=False),
        ),
    ]
