# Generated by Django 3.2.9 on 2022-11-10 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0040_auto_20221022_1646'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denuncias', '0004_alter_sinalizacaoperfil_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilsilenciado',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Perfil Silenciado'),
        ),
        migrations.AlterField(
            model_name='sinalizacaocomentario',
            name='comentario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Comentario', to='conteudos.comentario'),
        ),
        migrations.AlterField(
            model_name='sinalizacaoconteudo',
            name='conteudo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Conteudo', to='conteudos.conteudo'),
        ),
    ]
