# Generated by Django 3.2.9 on 2022-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_auto_20221109_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicosinalizacaoperfil',
            name='perfil',
            field=models.IntegerField(verbose_name='Perfil Sinalizado'),
        ),
    ]
