# Generated by Django 3.2.9 on 2022-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0008_alter_historicosinalizacaoconteudo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicosinalizacaoconteudo',
            name='status',
            field=models.CharField(choices=[('aguardando_edicao', 'Aguardando Edição'), ('edicao_concluida', 'Edição Concluída'), ('excluir_conteudo', 'Excluir Conteúdo'), ('parece_ok', 'Parece Ok')], max_length=255, verbose_name='Ação'),
        ),
    ]
