# Generated by Django 3.2.9 on 2022-11-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0040_auto_20221022_1646'),
        ('denuncias', '0009_alter_historicosinalizacaoconteudo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinalizacaoconteudo',
            name='conteudo',
            field=models.OneToOneField(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Conteudo', to='conteudos.conteudo'),
        ),
    ]
