# Generated by Django 3.2 on 2021-11-23 20:54

import conteudos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=False)),
            ],
            bases=(models.Model, conteudos.models.Ativo),
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
            bases=(models.Model, conteudos.models.Ativo),
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=False)),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudos.tecnologia')),
            ],
            options={
                'unique_together': {('nome', 'tecnologia')},
            },
            bases=(models.Model, conteudos.models.Ativo),
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='conteudos')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('thumbnail', models.FileField(upload_to='images')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('arquivo', 'Arquivo')], max_length=255)),
                ('ativo', models.BooleanField(default=False)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudos.secao')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='conteudos.Tag')),
            ],
            bases=(models.Model, conteudos.models.Ativo),
        ),
    ]
