# Generated by Django 3.2.9 on 2022-07-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudos.conteudo')),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudos.comentario')),
            ],
        ),
    ]
