# Generated by Django 3.2.9 on 2022-07-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0003_comentario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='criador',
        ),
    ]
