# Generated by Django 3.2.9 on 2022-07-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0004_alter_comentario_resposta'),
        ('conteudos', '0004_rename_usuario_comentario_criador'),
    ]

    operations = [
    ]
