# Generated by Django 3.2.9 on 2022-07-24 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0005_merge_20220720_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='dislike',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='dislike', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='like',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='like', to='auth.user'),
            preserve_default=False,
        ),
    ]
