# Generated by Django 3.2.9 on 2022-07-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0006_auto_20220724_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='like',
        ),
    ]
