# Generated by Django 3.2.9 on 2022-07-24 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0008_auto_20220724_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='dislike',
        ),
        migrations.AddField(
            model_name='comentario',
            name='criador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='criador', to='auth.user'),
            preserve_default=False,
        ),
    ]
