# Generated by Django 3.2.9 on 2022-07-25 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0012_alter_comentario_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
