# Generated by Django 3.2.9 on 2022-08-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0014_comentario_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='resposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta_set', to='conteudos.comentario'),
        ),
    ]
