# Generated by Django 3.2.9 on 2022-08-17 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0016_alter_comentario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='_conteudos_conteudo_dislike_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='_conteudos_conteudo_like_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
