# Generated by Django 3.2.9 on 2022-08-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0017_auto_20220817_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='visualizacao',
            field=models.IntegerField(default=0),
        ),
    ]
