# Generated by Django 3.2.9 on 2022-09-06 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0018_conteudo_visualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
