# Generated by Django 3.2.9 on 2022-09-11 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0019_conteudo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='visualizacao',
        ),
        migrations.AddField(
            model_name='conteudo',
            name='visualizacao',
            field=models.ManyToManyField(blank=True, related_name='_conteudos_conteudo_visualizacao_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
