# Generated by Django 3.2.9 on 2022-10-08 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0020_auto_20220911_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo', to='conteudos.conteudo')),
                ('visualizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
