# Generated by Django 3.2.9 on 2022-10-09 02:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0021_visualizacaolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizacaolog',
            name='conteudo',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='conteudo', to='conteudos.conteudo'),
        ),
        migrations.AlterField(
            model_name='visualizacaolog',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 23, 22, 41, 501032)),
        ),
    ]
