# Generated by Django 3.2.9 on 2022-10-09 05:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0024_alter_visualizacaolog_data'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='visualizacaolog',
            managers=[
                ('AltaManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
