# Generated by Django 3.2.9 on 2022-10-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0025_alter_visualizacaolog_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='visualizacaolog',
            managers=[
            ],
        ),
    ]
