# Generated by Django 3.2.9 on 2022-10-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0026_alter_visualizacaolog_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='like',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='like',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='visualizacao',
        ),
        migrations.RemoveField(
            model_name='visualizacaolog',
            name='visualizador',
        ),
    ]
