# Generated by Django 3.2.9 on 2022-10-09 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0028_auto_20221009_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizacaolog',
            name='visualizador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='visualizador', to='usuarios.perfil'),
            preserve_default=False,
        ),
    ]
