# Generated by Django 3.2.9 on 2022-10-14 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0031_auto_20221009_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizacaolog',
            name='visualizador',
        ),
        migrations.AddField(
            model_name='visualizacaolog',
            name='visualizador',
            field=models.ManyToManyField(related_name='visualizador', to=settings.AUTH_USER_MODEL),
        ),
    ]
