# Generated by Django 3.2.9 on 2022-10-14 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0032_auto_20221014_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisualizacaoLog',
            new_name='Visualizacao',
        ),
    ]
