# Generated by Django 3.2.9 on 2022-10-16 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0036_rename_visualizacaolog_visualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, to='conteudos.conteudo')),
                ('visualizador', models.ManyToManyField(related_name='_conteudos_historico_visualizador_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
