# Generated by Django 3.2.9 on 2022-10-19 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0038_alter_historico_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
