# Generated by Django 3.2.9 on 2022-10-22 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0039_comentario_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='baixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='carga',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='data_baixa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='responsavel_baixa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteudo_baixa', to=settings.AUTH_USER_MODEL),
        ),
    ]
